# CSCE 479/879 Hackathon: Saving/Loading, Regularization, and Batch Runs

Written by Eleanor Quint

Modified by Mrinal Rawool

Topics:
- Subclassing `tf.module`
- Saving and loading TensorFlow models
- Running TensorFlow-based Python programs in batch mode on the command line
- Overfitting, regularization, and early stopping

This is all setup in a IPython notebook so you can run any code you want to experiment with. Feel free to edit any cell, or add some to run your own code.

In [37]:
# We'll start with our library imports...
from __future__ import print_function

import numpy as np                 # to use numpy arrays
import tensorflow as tf            # to specify and run computation graphs
import tensorflow_datasets as tfds # to load training data
import matplotlib.pyplot as plt    # to visualize data and draw plots
from tqdm import tqdm              # to track progress of loops

DATA_DIR = './tensorflow-datasets/'

### Subclassing `tf.module`

The most flexible way to specify a model is by subclassing `tf.module`. 

This allows a model to be specified in a general way. 

The key function to implement is `__call__` which should take in data, run the model forward, and return the output. The function will frequently be decorated with `tf.function` (when not debugging the model), so that it can be compiled and run more quickly.

An example implementing a dense layer (generally you should use `tf.keras.layers.Dense`):

#### What is tf.function()?

Eager Mode: Used for debugging. Enabled in TF2.0 by default.
tf.function() or Graph mode: Faster computation

[tf.function](https://www.tensorflow.org/api_docs/python/tf/function)

[Tensorflow Graphs](https://www.tensorflow.org/guide/intro_to_graphs)

In [3]:
print(tf.__version__)
print(tf.executing_eagerly())

2.6.0
True


In [7]:
X = tf.ones([32,3])
print(X.shape)
print(X.shape[-1])

(32, 3)
3


In [35]:
class Dense(tf.Module):
    def __init__(self, output_size, activation=tf.nn.relu, name=None):
        super(Dense, self).__init__(name=name) # remember this call to initialize the superclass
        self.output_size = output_size
        self.activation = activation
        self.is_built = False

    def build(self, x):
        input_dim = x.shape[-1]
        self.w = tf.Variable(
          tf.random.normal([input_dim, self.output_size]), name='w')
        self.b = tf.Variable(tf.zeros([self.output_size]), name='b')
        self.is_built = True

    @tf.function
    def __call__(self, x):
        if not self.is_built:
            self.build(x)
        y = tf.matmul(x, self.w) + self.b
        return self.activation(y)

# Create an instance of the layer
dense_layer = Dense(10)
# Call the model by passing the input to it
dense_layer(tf.ones([32,3]))
# We can get the variables of a Module for used calculating and applying gradients with `.trainable_variables`
dense_layer.trainable_variables

# 32 x 3 (X)
# 3 x 10 (W)
# 10 (b)
# keras.activations.relu(x, 
#                        negative_slope=0.0, 
#                        max_value=None, 
#                        threshold=0.0) => max(x, 0), the element-wise maximum of 0 and the input tensor.

(<tf.Variable 'b:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'w:0' shape=(3, 10) dtype=float32, numpy=
 array([[ 0.88880134,  0.75868165, -0.732336  ,  0.18624711,  0.2891601 ,
          0.59838235, -0.5736517 ,  0.42830634, -0.94833237,  0.568252  ],
        [-0.16347186, -0.01391996, -1.0805752 , -0.8451594 , -0.7732344 ,
         -0.06365184,  0.7580231 , -0.05016793, -0.6843712 ,  1.2943755 ],
        [-0.5105442 ,  0.32958883,  0.562017  ,  0.25305784,  1.3924603 ,
         -2.7459097 ,  1.604529  ,  1.3659152 ,  1.6030265 , -0.92001396]],
       dtype=float32)>)

### Saving and Loading TensorFlow models

There are two main ways to save and load TF models: 
- `tf.train.Checkpoint`  
- `tf.SavedModel`


#### `tf.train.Checkpoint`. 
- It's best used in the process of training rather than for saving models. 
- This is because it only saves and loads the variables, and **not the structure of the model**. 

To use it, you must first instantiate the model from Python code and then load the variables

In [14]:
# we have to pass in the model (and anything else we want to save) as a kwarg
dense_layer = Dense(10)
optimizer = tf.keras.optimizers.Adam()
checkpoint = tf.train.Checkpoint(model=dense_layer, optimizer=optimizer)

# Save a checkpoint to /tmp/training_checkpoints-{save_counter}. 
# Every time checkpoint.save is called, the save counter is increased.
save_dir = checkpoint.save('/tmp/training_checkpoints')

# Restore the checkpointed values to the `model` object.
print("The save path is", save_dir)
status = checkpoint.restore(save_dir)
# we can check that everything loaded correctly, this is silent if all is well
print("Raises an exception if any variables are unmatched. \n", status.assert_consumed())

The save path is /tmp/training_checkpoints-1
Raises an exception if any variables are unmatched. 


#### `tf.SavedModel`

- saves the variables and structure of the model. 
- Specifically, it only saves methods which have been traced with `tf.function`.

In [23]:
# We can manually trace a function that has been decorated with tf.function using get_concrete_function
# We pass in the call signature. Here, None means that any number could fill in.
# Typically we don't have to do this explicitly, unless we want the None in the first dimension (as in the homework)
dense_layer = Dense(5) # was 10, changed to 5 for demo

# call using input spec
fn = dense_layer.__call__.get_concrete_function(x=tf.TensorSpec([None, 3], tf.float32))

# We can call the function we traced
print(fn(tf.ones([3,3]))) # X=> 3x3; W=> 3x10; b=> 10

tf.Tensor(
[[0.9622763 2.3470674 4.4509144 0.408059  0.       ]
 [0.9622763 2.3470674 4.4509144 0.408059  0.       ]
 [0.9622763 2.3470674 4.4509144 0.408059  0.       ]], shape=(3, 5), dtype=float32)


In [24]:
print("Saving model....")
tf.saved_model.save(dense_layer, '/tmp/saved_model')

Saving model....
INFO:tensorflow:Assets written to: /tmp/saved_model/assets


In [25]:
print(True) if "dense_layer" in locals() else print("False")

True


In [26]:
del dense_layer

print(True) if "dense_layer" in locals() else print("False")

False


In [27]:
restored_dense = tf.saved_model.load('/tmp/saved_model')

# this should be the same result as above
print(restored_dense(tf.ones([3,3])))

tf.Tensor(
[[0.9622763 2.3470674 4.4509144 0.408059  0.       ]
 [0.9622763 2.3470674 4.4509144 0.408059  0.       ]
 [0.9622763 2.3470674 4.4509144 0.408059  0.       ]], shape=(3, 5), dtype=float32)


### Running TensorFlow-based Python programs on HCC

#### 1. Get a shell on swan
To access a shell on swan's login node, you can run `ssh <username>@swan.unl.edu` or visit `swan-ood.unl.edu` in a browser. If you use the browser, login and then use the dropdown: `Clusters > Swan Shell Access`. Because this shell is on the login node, you shouldn't run your jobs directly. Instead, you can submit your job to a cluster node to be run with a GPU.

#### 2. Get the slurm submit script and set up your anaconda environment
Try this out by saving the following bash script as `submit_gpu.sh`.



```bash
#!/bin/sh
#SBATCH --time=6:00:00          # Maximum run time in hh:mm:ss
#SBATCH --mem=16000             # Maximum memory required (in megabytes)
#SBATCH --job-name=default_479  # Job name (to track progress)
#SBATCH --partition=cse479      # Partition on which to run job
#SBATCH --gres=gpu:1            # Don't change this, it requests a GPU
#SBATCH --constraint=gpu_t4

module load anaconda
conda activate /common/cse479/shared/envs/tensorflow-env # note env name
$@
```

#### 3. Submit a job
Once you've got your script, you can run it like so to submit a job: 
`sbatch submit_gpu.sh python <filepath>.py`. 
This will submit a job to the `cse479` partition. 

Each student is only allowed one job at a time on this partition, and you may check the status of your jobs with `squeue -u <username>`. 

If you would like to submit more than one job (which we encourage generally), you can submit the extras to the `cse479_preempt` partition by substituting in the line `#SBATCH --partition=cse479_preempt`. 

You can submit an unlimited number of jobs to this queue, but they may be interrupted anytime another student needs a gpu on the `cse479` partition and there are no others available. Thus, we reccomend saving your model periodically so that you can restart training from where it was interrupted rather than having to start all over again.

Other partitions on swan are available, including `gpu` and `guest_gpu`.  See [Partitions](https://hcc.unl.edu/docs/submitting_jobs/partitions/) and [Available Partitions](https://hcc.unl.edu/docs/submitting_jobs/partitions/swan_available_partitions/).

You can cancel jobs with `scancel <JOBID>`, where the job ID is the number associated with the job you can see in squeue or right after you submit the job, or with `scancel -u <username>` which cancels all your running jobs. For more details, please visit the [HCC docs](https://hcc.unl.edu/docs/), ask a question on Piazza, or come to office hours.

[List of GPUs](https://hcc.unl.edu/docs/submitting_jobs/submitting_gpu_jobs/)

[SLURM](https://hcc.unl.edu/docs/submitting_jobs/)

**if filename included inside SLURM**
```bash
# Script
...
module load anaconda
conda activate /common/cse479/shared/envs/tensorflow-env
python h3demo.py
```

```bash
# at the terminal
./submit_gpu_mr.sh
```

**else**
```bash
# Script
...
module load anaconda
conda activate /common/cse479/shared/envs/tensorflow-env
$@
```
```bash
# at the terminal
./submit_gpu_mr.sh python h3demo.py
```

In [ ]:
# To check job status
squeue -u <username>

# To cancel a particular job
scancel <JOBID>

### Overfitting, regularization, and early stopping

If we have enough parameters in our model, and little enough data, after a long period of training we begin to experience overfitting. Empirically, this is when the loss/classification error on the  training set continues to drop while the loss/classification error on the test/validation data increases. It means that the model is looking for patterns specific to the training data that won't generalize to future, unseen data. This is a problem.

Solutions? Here are some first steps to think about:
1. Get more data for the training set
2. Reduce the number of model parameters
3. Regularize the scale of the model parameters
4. Regularize using dropout
5. Early Stopping

We'll go over how to do 3, 4, and 5 here.

#### L2 Regularization
We calculate l2 loss on the value of the weight matrix, so it's invariant to the input value. We'll add the regularization loss value to the total loss value so that it's included in the gradient update. 

[tf.nn.l2_loss](https://www.tensorflow.org/api_docs/python/tf/nn/l2_loss)

In [30]:
L2_COEFF = 0.1 # Controls how strongly to use regularization

class L2DenseNetwork(tf.Module):
    def __init__(self, name=None):
        super(L2DenseNetwork, self).__init__(name=name) # remember this call to initialize the superclass
        self.dense_layer1 = tf.keras.layers.Dense(32, activation=tf.nn.relu)
        self.dense_layer2 = tf.keras.layers.Dense(10)
        
    def l2_loss(self):
        # Make sure the network has been called at least once to initialize the dense layer kernels
        return tf.nn.l2_loss(self.dense_layer1.kernel) + tf.nn.l2_loss(self.dense_layer2.kernel)

    @tf.function
    def __call__(self, x):
        embed = self.dense_layer1(x) # 1x100, 100x32, 32
        output = self.dense_layer2(embed) # 1x32, 32x10, 10
        return output

In [29]:
# Defining, creating and calling the network repeatedly will trigger a WARNING about re-tracing the function
# So we'll check to see if the variable exists already
if 'l2_dense_net' not in locals():
    l2_dense_net = L2DenseNetwork()


l2_dense_net(tf.ones([1, 100]))


<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.5222647 ,  2.0502682 ,  0.84439796,  0.6679952 , -0.9826426 ,
        -1.098808  , -0.47519553, -0.30028853,  0.41872552,  1.2211578 ]],
      dtype=float32)>

In [31]:
l2_loss = l2_dense_net.l2_loss()                     # calculate l2 regularization loss

cross_entropy_loss = 0.                              # calculate the classification loss

total_loss = cross_entropy_loss + L2_COEFF * l2_loss # and add to the total loss, then calculate gradients

#### Dropout

Let's re-specify the network with regularization from [dropout](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout). The Dropout layer randomly sets values to 0 with a frequency of the `rate` input (given when the layer is constructed). Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

In [38]:
class DropoutDenseNetwork(tf.Module):
    def __init__(self, name=None):
        super(DropoutDenseNetwork, self).__init__(name=name) # remember this call to initialize the superclass
        self.dense_layer1 = Dense(32)
        self.dropout = tf.keras.layers.Dropout(0.2)
        self.dense_layer2 = Dense(10, activation=tf.identity)

    @tf.function # = graph mode
    def __call__(self, x, is_training):
        
        embed = self.dense_layer1(x)
        propn_zero_before = tf.reduce_mean(tf.cast(tf.equal(embed, 0.), tf.float32))
        embed = self.dropout(embed, is_training)
        propn_zero_after = tf.reduce_mean(tf.cast(tf.equal(embed, 0.), tf.float32))
        # Note that in a tf.function, we have to use tf.print to print the value of tensors
        tf.print('Zeros before and after:', propn_zero_before, "and", propn_zero_after)
        # tf.print("tf.executing_eagerly(): ", tf.executing_eagerly()) # <------------------- uncomment this (1)
        output = self.dense_layer2(embed)
        return output

In [39]:
# Defining, creating and calling the network repeatedly will trigger a WARNING about re-tracing the function
# So we'll check to see if the variable exists already

# del drop_dense_net # <------------------- uncomment this (2)
if 'drop_dense_net' not in locals():
    drop_dense_net = DropoutDenseNetwork()
    

drop_dense_net(tf.ones([1, 100]), tf.constant(True))
print("Something to think about: why isn't the difference exactly equal to the proportion we passed to dropout?")

Zeros before and after: 0.4375 and 0.5
Something to think about: why isn't the difference exactly equal to the proportion we passed to dropout?


In [21]:
print(tf.executing_eagerly())

True


In [38]:
type(locals())

dict

In [37]:
locals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'print_function', 'np', 'tf', 'tfds', 'plt', 'tqdm', 'DATA_DIR', '_i2', '_i3', 'Dense', '_3', '_i4', '_4', '_i5', 'X', '_i6', '_i7', '_i8', 'optimizer', 'checkpoint', 'save_dir', 'status', '_8', '_i9', '_9', '_i10', '_i11', 'fn', 'restored_dense', '_i12', '_i13', 'DropoutDenseNetwork', 'drop_dense_net', 'sys', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i20', '_i21', '_i22', '_i23', '_i24', '_24', '_i25', 'item', '_i26', '_i27', '_27', '_i28', '_28', '_i29', '_29', '_i30', '_30', '_i31', '_i32', '_32', '_i33', '_i34', '_34', '_i35', '_i36', '_i37'])

In [32]:
locals()['__name__']

'__main__'

#### Early Stopping

Each gradient descent update takes only a small step, so we want to look at each input datum many times. How do we know when to stop, though? We want to keep training until improvement stops, but because neural networks are non-linear, they might get worse before they get better, so we don't want to stop them after getting worse one time. We'll use the following code to do "early stopping" with patience. We pass in the validation loss (Note: make sure you use validation loss, not training loss. This is important) and `check` will tell us whether we should stop. It will return `True` after the loss hasn't improved for `patience` epochs.

Although you might choose whether or not the last two regularizers are appropriate based on the problem, you should always use early stopping.

In [34]:
class EarlyStopping:
    def __init__(self, patience=2, epsilon=1e-4): # orig 5. changed to 2 for demo
        """
        Args:
            patience (int): how many epochs of not improving before stopping training
            epsilon (float): minimum amount of improvement required to reset counter
        """
        self.patience = patience
        self.epsilon = epsilon
        self.best_loss = float('inf')
        self.epochs_waited = 0
    
    def __str__(self):
        return "Early stopping has waited {} epochs out of {} at loss {}".format(self.epochs_waited, self.patience, self.best_loss)
        
    def check(self, loss):
        """
        Call after each epoch to check whether training should halt
        
        Args:
            loss (float): loss value from the most recent epoch of training
            
        Returns:
            True if training should halt, False otherwise
        """
        if loss < (self.best_loss - self.epsilon):
            self.best_loss = loss
            self.epochs_waited = 0
            return False
        else:
            self.epochs_waited += 1
            return self.epochs_waited > self.patience
            
early_stop_module = EarlyStopping()
# pass in validation loss at each training epoch
print("Training...")
print("Should we stop training?", early_stop_module.check(1.4))
print(early_stop_module)
print("Training...")
print("Should we stop training?", early_stop_module.check(2.3))
print(early_stop_module)
print("Training...")
print("Should we stop training?", early_stop_module.check(1.2))
print(early_stop_module)
print("Training...")
print("Should we stop training?", early_stop_module.check(1.2))
print(early_stop_module)
print("Training...")
print("Should we stop training?", early_stop_module.check(1.2))
print(early_stop_module)
print("Training...")
print("Should we stop training?", early_stop_module.check(1.2))
print(early_stop_module)

Training...
Should we stop training? False
Early stopping has waited 0 epochs out of 2 at loss 1.4
Training...
Should we stop training? False
Early stopping has waited 1 epochs out of 2 at loss 1.4
Training...
Should we stop training? False
Early stopping has waited 0 epochs out of 2 at loss 1.2
Training...
Should we stop training? False
Early stopping has waited 1 epochs out of 2 at loss 1.2
Training...
Should we stop training? False
Early stopping has waited 2 epochs out of 2 at loss 1.2
Training...
Should we stop training? True
Early stopping has waited 3 epochs out of 2 at loss 1.2


### Homework

Your homework is to complete the following two tasks:
1. Make sure you're comfortable submitting jobs on swan and saving models. Submit a job to `cse479` and put the job id from the submission in a text file along with the other information given by `squeue`.
2. Think about the question posed above about dropout: "Why isn't the difference between the number of zeros before and after applying dropout exactly equal to the dropout proportion?" Consider the network architecture and what operations were run before the dropout layer. Write a few sentences about this in the same text file as the previous question and submit to Canvas.

In addition to your text file, submit your `.py` file that implements model saving.

I'm expecting this to take about an hour (or less if you're experienced). Feel free to use any code from this or previous hackathons. If you don't understand how to do any part of this or if it's taking you longer than that, please let me know in office hours or by email (both can be found on the syllabus). I'm also happy to discuss if you just want to ask more questions about anything in this notebook!